general:
  kafka-topic: trader-updates

spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: midas-core
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"